---
title: "About"
description: |
  About this Project
---
# Motivation #
Economics is always been my favorite subject since middle school, and I later decided that I am going to achieve this road for the rest of my life. Housing on the other hand lies in this field perfectly, as it could be huge to the scale like the 2008 Market Crash, and Japanese asset price bubble, it could also be small to each one of us as it's one of the basic needs of Human. So I decided to do this project as my final project for this bootcamp also the first official website I made out of interest,it represents an milestone on my student career. 

# Solution #
Combining all four Analysis on the previous tab, the two key factors that influenced housing prices is Income and Housing Supply, this matched the demand and supply model in economics where the demand and supply curve determined the price of certain goods. If the demand rises, in this case demand will rise if income rises because people will have more free money to buy a house, and the supply drop in this case the housing supply, the housing prices will rise. Vice versa, if demand decreases and supply dramaticlly increases like during the 2008 crash, the housing price will falls, I am sure that there is definitely other factors that might influenced housing prices includes local markets, location, interest rate, credit scores, etc. All of which include the population (which might seems insignificant) will have a certain degree of influenced on housing prices, I just picked out three that is what I think influenced the most (it turns out only two of them).

# About Me #
Yuhan Wu is an incoming sophomore at Newton North High School(Class of 2024) located in Newton, MA, US. Interests include economics, debate,and piano. 