---
title: "Housing Fluctuation using Case-Shiller Index"
description: |
  This project is about observing and analysing the housing fluctuation of an single familly house from 1987 to Janurary 2021 of three cities: Boston, New York City and San Francisco. 
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(lubridate)
library(dplyr)
library(plotly)
library(gganimate)
library(gifski)
library(png)
library(patchwork)
library(gapminder)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages
```

```{r}
raw_data_BO <- read.csv("BOXRSA.csv")
raw_data_NY <- read.csv("NYXRSA.csv")
raw_data_SF <- read.csv("SFXRSA.csv")

data_BO <- raw_data_BO %>%
mutate(City="Boston") %>%
mutate(Data= BOXRSA)

data_NY <- raw_data_NY %>%
  mutate(City="New York")%>%
  mutate(Data= NYXRSA)

data_SF <- raw_data_SF %>%
  mutate(City ="San Francisco")%>%
mutate(Data= SFXRSA)

clean_data <-bind_rows(data_BO,data_NY,data_SF)
```

```{r,echo=FALSE}
data_final <- clean_data %>%
select(DATE,Data,City)%>%
  group_by(City) 
```

```{r}
data_plotly <- data_final%>%
ggplot(mapping=aes(x = DATE,y=Data,color=City,group=1, text = paste("Date:",DATE, "\n")))+
  geom_line()+
  scale_x_discrete(breaks=12)+
  labs(title="Housing Price Fluctuation of Three Major Cities In US",x="Time (1987-2021)",y="Case-Shiller index")

   ggplotly(data_plotly, tooltip = "text")
     
```

# Analysis #
San Francisco endured the greatest decline in 2008 Housing bubble, as well as the greatest increased after the crash, and for all three cities housing price shows an upward sloping trend, which means that the value of an single-family house keep increasing over time. 