---
title: "Thanks"
description: |
  Experience and thanks to all who supported me and help with along the four weeks of this bootcamp. And thank you all for listening and asking questions during my presentation. 
output: distill::distill_article
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
## Experience and Thanks ##
This is the first official websites I created on my own, I spends hours and days trying to figuring out which data best suits this project, as well as what code should I write to make this project possible. I give my sincere thanks to Preceptor Kane and the TFs, with the class lecture and tutorials, start from creating visualization to making a project, I've learned a lot, if I would do everything by myself, I wouldn't be able to reach this far and getting this nice looking graph on your screen without the support from them, my second thanks is to my parents who supported me through the heavy workload, as I have both math and data science on the same day, and last but not least my great thanks to my math teacher Ms.Widener who recommended this course to me, without here I wouldn't be able to have this wonderful experience. 




